# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.

# Solution using XOR

def diff(s1, s2):

    ans = 0

    for i in s1+s2:
        ans ^= ord(i)

    return chr(ans)


s1 = 'abcd'
s2 = 'aecdb'

print(diff(s1, s2))
